// Vue.js/01. Working with report designer/src/App.vue
<template>
  <div id="app">
    <div>
      <h2>Stimulsoft Reports.JS Designer</h2>
      <div id="designer"></div>
    </div>
  </div>
</template>

<script>

export default {
  name: 'app',
  data () {
    return {
    
    }
  },
  created: function() {
    console.log('Loading Designer view');

    console.log('Set full screen mode for the designer');
    var options = new window.Stimulsoft.Designer.StiDesignerOptions();
    options.appearance.fullScreenMode = false;

    console.log('Create the report designer with specified options');
    var designer = new window.Stimulsoft.Designer.StiDesigner(options, 'StiDesigner', false);

    console.log('Create a new report instance');
    var report = new window.Stimulsoft.Report.StiReport();

    console.log('Load report from url');
    report.loadFile('reports/SimpleList.mrt');

    console.log('Edit report template in the designer');
    designer.report = report;

    console.log('Rendering the viewer to selected element');
    designer.renderHtml('designer');

    console.log('Loading completed successfully!');
  }
}
</script>

<style>
</style>

// React/Integrating the Report Designer into an Application (TypeScript)/src/App.tsx
import React from 'react';
import {Stimulsoft} from 'stimulsoft-reports-js/Scripts/stimulsoft.blockly.editor';
import 'stimulsoft-reports-js/Css/stimulsoft.designer.office2013.whiteblue.css';
import 'stimulsoft-reports-js/Css/stimulsoft.viewer.office2013.whiteblue.css';
import './App.css';

class App extends React.Component {
    private options: any;
    private designer: any;

    render() {
        return (
            <div id="designer" className="App">
            </div>
        );
    }

    componentDidMount() {
        console.log('Loading Designer view');

        console.log('Set full screen mode for the designer');
        this.options = new Stimulsoft.Designer.StiDesignerOptions();
        this.options.appearance.fullScreenMode = false;

        console.log('Create the report designer with specified options');
        this.designer = new Stimulsoft.Designer.StiDesigner(this.options, 'StiDesigner', false);

        console.log('Edit report template in the designer');
        this.designer.report = new Stimulsoft.Report.StiReport();

        console.log('Load report from url');
        this.designer.report.loadFile('/reports/SimpleList.mrt');

        console.log('Rendering the designer to selected element');
        this.designer.renderHtml('designer');

        console.log('Loading completed successfully!');
    }

}

export default App;
