// Angular/Integrating the Report Viewer into an Application/src/app/app.component.ts
import { Component } from '@angular/core';
import { ViewEncapsulation } from '@angular/core';
import { Http } from '@angular/http';
import { Response } from '@angular/http';
import { Stimulsoft } from 'stimulsoft-reports-js/Scripts/stimulsoft.viewer'

@Component({
  selector: 'app-root',
  template: `<div>
                  <h2>Stimulsoft Reports.JS Viewer</h2>
                  <div id="viewer"></div>
              </div>`,
  encapsulation: ViewEncapsulation.None
})
export class AppComponent {
  viewer: any = new Stimulsoft.Viewer.StiViewer(null, 'StiViewer', false);
  report: any = new Stimulsoft.Report.StiReport();

  ngOnInit() {
    console.log('Loading Viewer view');

    this.http.request('reports/Report.mdc').subscribe((data: Response) => {

      console.log('Load report from url');
      this.report.loadDocument(data.text());
      this.viewer.report = this.report;

      console.log('Rendering the viewer to selected element');
      this.viewer.renderHtml('viewer');
    });
  }

  constructor(private http: Http) {

  }
}

// React/Integrating the Report Viewer into an Application (TypeScript)/src/App.tsx
import React from 'react';
import { Stimulsoft } from 'stimulsoft-reports-js/Scripts/stimulsoft.viewer';
import 'stimulsoft-reports-js/Css/stimulsoft.viewer.office2013.whiteblue.css';
import './App.css';

class App extends React.Component {
    private viewer = new Stimulsoft.Viewer.StiViewer(undefined, 'StiViewer', false);
    private report = new Stimulsoft.Report.StiReport();

    render() {
        return (
            <div id="viewer" className="App">
            </div>
        );
    }

    async componentDidMount() {
        console.log('Loading Viewer view');

        const response = await fetch('/reports/Report.mdc');
        const data = await response.json();
        console.log('Load report from url');
        this.report.loadDocument(data);
        this.viewer.report = this.report;

        console.log('Rendering the viewer to selected element');
        this.viewer.renderHtml('viewer');
    }

}

export default App;
